[package]
name = "stereotyping"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk = { version = "0.9.3", package = "gtk4", features = ["v4_16", "gnome_47"] }
adw = { version = "0.7.1", package = "libadwaita", features = ["v1_6"] }
gio = { version = "0.20.5", features = ["v2_82"] }
